-- Trino-style distributed query examples for AutoOps operational telemetry.
-- These queries assume warehouse-ready fact/dimension outputs generated by AutoOps.

-- 1. Service-health summary by day
SELECT
  s.service_name,
  h.event_day,
  h.event_count,
  h.avg_latency_ms,
  h.avg_error_rate,
  h.anomaly_count
FROM fact_service_health_daily h
JOIN dim_service s
  ON h.service_id = s.service_id
WHERE h.event_day >= current_date - INTERVAL '7' DAY
ORDER BY h.anomaly_count DESC, h.avg_latency_ms DESC;

-- 2. Top anomaly-producing services
SELECT
  s.service_name,
  COUNT(*) AS anomaly_events,
  AVG(e.latency_ms) AS avg_latency_ms,
  AVG(e.error_rate) AS avg_error_rate
FROM fact_operational_event e
JOIN dim_service s
  ON e.service_id = s.service_id
WHERE e.anomaly_flag = true
GROUP BY s.service_name
ORDER BY anomaly_events DESC;

-- 3. Regional latency trend
SELECT
  r.region_name,
  date_trunc('hour', e.event_timestamp) AS event_hour,
  AVG(e.latency_ms) AS avg_latency_ms,
  COUNT(*) AS event_count
FROM fact_operational_event e
JOIN dim_region r
  ON e.region_id = r.region_id
GROUP BY r.region_name, date_trunc('hour', e.event_timestamp)
ORDER BY event_hour DESC, avg_latency_ms DESC;

-- 4. Service-owner dashboard query
SELECT
  s.owner_team,
  s.service_name,
  COUNT(*) AS total_events,
  SUM(CASE WHEN e.anomaly_flag THEN 1 ELSE 0 END) AS anomaly_events,
  AVG(e.latency_ms) AS avg_latency_ms,
  AVG(e.error_rate) AS avg_error_rate
FROM fact_operational_event e
JOIN dim_service s
  ON e.service_id = s.service_id
GROUP BY s.owner_team, s.service_name
ORDER BY anomaly_events DESC, avg_latency_ms DESC;

-- 5. Anomaly drilldown query
SELECT
  e.event_id,
  s.service_name,
  r.region_name,
  e.event_type,
  e.latency_ms,
  e.error_rate,
  e.event_timestamp
FROM fact_operational_event e
JOIN dim_service s
  ON e.service_id = s.service_id
JOIN dim_region r
  ON e.region_id = r.region_id
WHERE e.anomaly_flag = true
ORDER BY e.event_timestamp DESC;
